# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.ssh.insert_key = false
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.box_check_update = false

  config.vm.define "homestead" do |homestead|
    homestead.vm.hostname = "homestead"
    homestead.vm.network "private_network", ip: "192.168.56.10"
    # homestead.vm.synced_folder "../data", "/vagrant_data"
    # homestead.vm.synced_folder ".", "/vagrant", disabled: true
    homestead.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "homestead"
      vb.memory = "4096"
      vb.cpus = "2"
    end

    # homestead.vm.provision "shell", path: "scripts/script.sh", run: "always"
    homestead.vm.provision "shell", inline: <<-SHELL
      apt-get update
    SHELL

  end

end
